import React from "react";

function Home() {
  return (
    <div className="homepage">
      <div className="homepage-title-container">
        <div className="homepage-title">
          <h1>A.I. Learn Spanish</h1>
        </div>
      </div>
      <div className="homepage-desc-container">
        <div className="homepage-desc">
          <h2>
            Welcome to A.I. Learn Spanish, an interactive way to delve into
            learning a new language. Enjoy personalized stories and flashcards
            aimed to increase retention and language learning.
          </h2>
        </div>
      </div>
      <div className="why-learn-container">
        <div className="why-learn-card">
          <div className="why-learn-text">
            <h1>Why learn Spanish?</h1>
            <h2>
              Learning Spanish unlocks significant professional and personal
              benefits by facilitating global communication and cultural
              immersion. Professionally, it offers a competitive edge in the job
              market, enabling direct engagement with Spanish-speaking
              colleagues, clients, and partners across numerous countries. This
              linguistic skill enhances career opportunities and operational
              efficiency in an increasingly globalized economy. Personally,
              speaking Spanish enriches cultural experiences, allowing for
              deeper connections with Spanish-speaking communities and a fuller
              appreciation of Hispanic cultures, literature, and arts. It also
              improves cognitive abilities and promotes cultural empathy, making
              travel more immersive and rewarding. Essentially, mastering
              Spanish is not just about learning another language—it's about
              embracing a global perspective and fostering cross-cultural
              understanding in a multicultural world.
            </h2>
          </div>
          <div className="why-learn-image-container">
            <div className="why-learn-image" />
          </div>
        </div>
      </div>
      <div className="homepage-learning-selection">
        <div className="learning-selection-header">
          <h2> Learn from a variety of different tools!</h2>
        </div>
        <div className="learning-tools-selection">
          <div className="learning-tools-item">
            <h2>Flashcards</h2>
            <h3>
              Utilize flashcards to master new vocabulary words. As you advance,
              the content will adapt to highlight areas requiring improvement.
            </h3>
          </div>
          <div className="learning-tools-item">
            <h2>Story Time</h2>
            <h3>
              Receive customized stories generated by A.I., focusing on areas
              where you need improvement.
            </h3>
          </div>
          <div className="learning-tools-item">
            <h2>Tool 3</h2>
            <h3>TBD</h3>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Home;
